version: "3.9"

services:
  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 2g
    ports:
      - "4444:4444"

  tests:
    build: .
    container_name: insider-automation-tests
    environment:
      BROWSER: "chrome"
      HEADLESS: "true"
      SELENIUM_URL: "http://selenium:4444/wd/hub"
    volumes:
      - ./allure-results:/usr/src/app/allure-results
    depends_on:
      - selenium
    command: mvn -B clean test
